server:
  port: 8204


spring:
  application:
    # 服务名
    name: service-msm

  # 环境设置 dev、test、prod
  profiles:
    active: dev

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.50.133:8848

  redis:
    host: 192.168.50.133
    port: 6379
