server:
  port: 8201


spring:
  application:
    # 服务名
    name: service-hosp

  # 环境设置 dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1759714344x

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 解决swagger与springboot不兼容的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/hilda/mapper/*.xml
  type-aliases-package: com.hilda.yygh.model
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
