server:
  port: 8202

spring:
  cache:
    type: redis
  application:
    name: service-cmn
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1759714344x
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 解决swagger与springboot不兼容的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 192.168.50.133
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.50.133:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/hilda/mapper/*.xml
  type-aliases-package: com.hilda.yygh.model
